services:
  - type: web
    name: college-erp-backend
    env: java
    region: oregon
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx512m -jar target/erp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: MAVEN_VERSION
        value: "3.9"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college-erp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /actuator/health

databases:
  - name: college-erp-db
    databaseName: college_erp
    user: college_erp_user
    plan: free
